Repository catchorg/Catch2, pull requests merged in 2019-01, with the labels that each got.

#1492 fix #1394: avoid superfluous re-run when specific section is selected
  include/internal/catch_test_case_tracker.cpp
  include/internal/catch_test_case_tracker.h
  misc/coverage-helper.cpp
  projects/CMakeLists.txt
  projects/SelfTest/IntrospectiveTests/PartTracker.tests.cpp
Labels: BugFix

#1484 contributing.md: Add build instructions
  docs/contributing.md
Labels: Documentation

#1452 ParseAndAddCatchTests: Add PARSE_CATCH_TESTS_HIDDEN_TESTS_DISABLED option
  contrib/ParseAndAddCatchTests.cmake
Labels: Contrib

#1516 WIP: Generators take 2
  docs/generators.md
  docs/list-of-examples.md
  examples/300-Gen-OwnGenerator.cpp
  examples/310-Gen-VariablesInGenerators.cpp
  examples/CMakeLists.txt
  include/internal/catch_generators.cpp
  include/internal/catch_generators.hpp
  include/internal/catch_interfaces_generatortracker.h
  include/internal/catch_run_context.cpp
  include/internal/catch_test_case_tracker.cpp
  include/internal/catch_test_case_tracker.h
  projects/SelfTest/Baselines/compact.sw.approved.txt
  projects/SelfTest/Baselines/console.std.approved.txt
  projects/SelfTest/Baselines/console.sw.approved.txt
  projects/SelfTest/Baselines/junit.sw.approved.txt
  projects/SelfTest/Baselines/xml.sw.approved.txt
  projects/SelfTest/IntrospectiveTests/GeneratorsImpl.tests.cpp
  projects/SelfTest/UsageTests/Generators.tests.cpp
Labels: Feature
