Repository catchorg/Catch2, pull requests merged in 2019-07, with the labels that each got.

#1682 Update Contents in docs #1667
  docs/command-line.md
  docs/contributing.md
Labels: Documentation

#1686 Add `std::byte` support
  include/internal/catch_compiler_capabilities.h
  include/internal/catch_tostring.cpp
  include/internal/catch_tostring.h
  projects/CMakeLists.txt
  projects/SelfTest/UsageTests/ToStringByte.tests.cpp
Labels: Tweak

#1700 Fix typo in 2.7.1 release notes
  docs/release-notes.md
Labels: Documentation

#1697 Fix non-default-constructible type lists used in TEMPLATE_LIST_TEST_CASE
  include/internal/catch_test_registry.h
  projects/SelfTest/Baselines/compact.sw.approved.txt
  projects/SelfTest/Baselines/console.std.approved.txt
  projects/SelfTest/Baselines/console.sw.approved.txt
  projects/SelfTest/Baselines/junit.sw.approved.txt
  projects/SelfTest/Baselines/xml.sw.approved.txt
  projects/SelfTest/UsageTests/Misc.tests.cpp
Labels: BugFix

#1698 Fix CTest command issue with square brackets
  contrib/CatchAddTests.cmake
Labels: BugFix, Contrib

#1706 Fix xml reporter crashing when a benchmark failed.
  include/reporters/catch_reporter_xml.cpp
  include/reporters/catch_reporter_xml.h
Labels: BugFix
