Repository catchorg/Catch2, pull requests merged in 2019-10, with the labels that each got.

#1764 update name of Value Generators in doc to match class names
  docs/generators.md
  include/internal/catch_generators.hpp
Labels: Documentation

#1765 Add Cataclysm:Dark Days Ahead to project list
  docs/opensource-users.md
Labels: Documentation

#1769 Patch:Failure to pass special chars through input file
  include/internal/catch_test_spec_parser.cpp
  include/internal/catch_test_spec_parser.h
  projects/CMakeLists.txt
  projects/SelfTest/Misc/plain-old-tests.input
  projects/SelfTest/Misc/special-characters-in-file.input
Labels: BugFix

#1779 add a note how to run selftests using multiconfig generators
  docs/contributing.md
Labels: Development, Documentation

#1770 Patch: Catch terminates when parsing invalid test name from input file
  include/internal/catch_commandline.cpp
  include/internal/catch_interfaces_reporter.h
  include/internal/catch_session.cpp
  include/internal/catch_test_spec.cpp
  include/internal/catch_test_spec.h
  include/internal/catch_test_spec_parser.cpp
  include/internal/catch_test_spec_parser.h
  include/reporters/catch_reporter_bases.hpp
  include/reporters/catch_reporter_console.cpp
  include/reporters/catch_reporter_console.h
  include/reporters/catch_reporter_listening.cpp
  include/reporters/catch_reporter_listening.h
Labels: BugFix

#1735 Suppress false positive from clang-analyzer
  include/internal/catch_context.h
Labels: Warnings issue

#1783 docs: command-line: Add example to specify tests by file name.
  docs/command-line.md
Labels: Documentation

#1776 Enable floating point ranges
  docs/generators.md
  include/internal/catch_generators_specific.hpp
  projects/SelfTest/Baselines/compact.sw.approved.txt
  projects/SelfTest/Baselines/console.std.approved.txt
  projects/SelfTest/Baselines/console.sw.approved.txt
  projects/SelfTest/Baselines/junit.sw.approved.txt
  projects/SelfTest/Baselines/xml.sw.approved.txt
  projects/SelfTest/IntrospectiveTests/GeneratorsImpl.tests.cpp
Labels: Tweak

#1719 Improve JUnit failure report
  include/reporters/catch_reporter_junit.cpp
  projects/SelfTest/Baselines/junit.sw.approved.txt
Labels: Tweak

#1791 Rework how warning suppression in macros is done
  include/internal/benchmark/detail/catch_stats.cpp
  include/internal/catch_capture.hpp
  include/internal/catch_compiler_capabilities.h
  include/internal/catch_interfaces_exception.h
  include/internal/catch_reporter_registrars.hpp
  include/internal/catch_section.h
  include/internal/catch_tag_alias_autoregistrar.h
  include/internal/catch_test_registry.h
  projects/SelfTest/UsageTests/Misc.tests.cpp
Labels: Tweak
