Repository catchorg/Catch2, pull requests merged in 2019-02, with the labels that each got.

#1544 Use correct type name instead of index for TEMPLATE_PRODUCT_TEST_CASE
  include/internal/catch_preprocessor.hpp
  include/internal/catch_test_registry.h
  projects/SelfTest/Baselines/compact.sw.approved.txt
  projects/SelfTest/Baselines/console.std.approved.txt
  projects/SelfTest/Baselines/console.sw.approved.txt
  projects/SelfTest/Baselines/junit.sw.approved.txt
  projects/SelfTest/Baselines/xml.sw.approved.txt
Labels: Tweak

#1537 Fix -Wdefaulted-function-deleted warning
  include/internal/catch_interfaces_reporter.h
Labels: Warnings issue

#1524 fix an issue where approvalTests.py cannot find selfTest.exe executable
  scripts/scriptCommon.py
Labels: In progress

#1526 Reimplementing RangeGenerator
  docs/generators.md
  include/internal/catch_generators.hpp
  projects/SelfTest/Baselines/compact.sw.approved.txt
  projects/SelfTest/Baselines/console.std.approved.txt
  projects/SelfTest/Baselines/console.sw.approved.txt
  projects/SelfTest/Baselines/junit.sw.approved.txt
  projects/SelfTest/Baselines/xml.sw.approved.txt
  projects/SelfTest/IntrospectiveTests/GeneratorsImpl.tests.cpp
Labels: Feature
