Repository catchorg/Catch2, pull requests merged in 2020-12, with the labels that each got.

#2111 Use snprintf instead of sprintf
  src/catch2/reporters/catch_reporter_combined_tu.cpp
Labels: Tweak

#2120 Add deprecation warning in ParseAndCatchTests
  contrib/ParseAndAddCatchTests.cmake
  docs/cmake-integration.md
  docs/deprecations.md
Labels: Contrib, Documentation

#2125 Fix Wold-style-cast error
  CMake/MiscFunctions.cmake
  src/catch2/benchmark/detail/catch_stats.cpp
  src/catch2/benchmark/detail/catch_stats.hpp
  tests/SelfTest/Baselines/compact.sw.approved.txt
  tests/SelfTest/Baselines/console.sw.approved.txt
  tests/SelfTest/Baselines/tap.sw.approved.txt
  tests/SelfTest/Baselines/xml.sw.approved.txt
  tests/SelfTest/IntrospectiveTests/String.tests.cpp
  tests/SelfTest/IntrospectiveTests/Xml.tests.cpp
Labels: Warnings issue

#2138 Split some configuration options out of catch_compiler_capabilities
  src/CMakeLists.txt
  src/catch2/catch_all.hpp
  src/catch2/catch_session.hpp
  src/catch2/catch_tag_alias_autoregistrar.hpp
  src/catch2/catch_tostring.hpp
  src/catch2/internal/catch_compiler_capabilities.hpp
  src/catch2/internal/catch_config_counter.hpp
  src/catch2/internal/catch_config_wchar.hpp
  src/catch2/internal/catch_main.cpp
  src/catch2/internal/catch_source_line_info.hpp
  src/catch2/internal/catch_test_case_tracker.hpp
  src/catch2/internal/catch_test_registry.hpp
  src/catch2/internal/catch_xmlwriter.hpp
  src/catch2/reporters/catch_reporter_compact.cpp
  tests/SelfTest/UsageTests/Misc.tests.cpp
Labels: Refactoring
