Repository catchorg/Catch2, pull requests merged in 2020-09, with the labels that each got.

#2016 Fix unintended colouring of user's stderr on POSIX
  src/catch2/internal/catch_console_colour.cpp
Labels: BugFix

#2013 Make experimental capture work on Windows with read-write temp file b…
  include/internal/catch_output_redirect.cpp
Labels: BugFix

#2022 fixes bug in example - undeclared identifier
  docs/generators.md
Labels: Documentation

#2027 Disable __builtin_constant_p when compiling with nvcc
  include/internal/catch_compiler_capabilities.h
Labels: 3rd party bug, Tweak

#2028 Docu/Show how to use CMake FetchContent
  docs/cmake-integration.md
Labels: Documentation

#2023 Add REPORTER and OUTPUT_DIR args to catch_discover_tests
  contrib/Catch.cmake
  contrib/CatchAddTests.cmake
  docs/cmake-integration.md
Labels: Contrib
