Repository catchorg/Catch2, pull requests merged in 2020-02, with the labels that each got.

#1846 Make CATCH_BREAK_INTO_DEBUGGER be user-configurable
  docs/configuration.md
  include/internal/catch_debugger.h
Labels: Tweak

#1854 catch_compiler_capabilities.h: use proper math define
  include/internal/catch_compiler_capabilities.h
  include/internal/catch_matchers_floating.cpp
Labels: BugFix

#1860 Fix typo in link in docs
  docs/commercial-users.md
Labels: Documentation

#1866 Add command line option 'never' to --wait-for-keypress
  docs/command-line.md
  include/internal/catch_commandline.cpp
  projects/SelfTest/Baselines/compact.sw.approved.txt
  projects/SelfTest/Baselines/console.std.approved.txt
  projects/SelfTest/Baselines/console.sw.approved.txt
  projects/SelfTest/Baselines/junit.sw.approved.txt
  projects/SelfTest/Baselines/sonarqube.sw.approved.txt
  projects/SelfTest/Baselines/xml.sw.approved.txt
  projects/SelfTest/IntrospectiveTests/CmdLine.tests.cpp
Labels: Tweak

#1843 Feature: generic matchers
  src/CMakeLists.txt
  src/catch2/catch_capture_matchers.cpp
  src/catch2/catch_capture_matchers.h
  src/catch2/catch_matchers_templates.cpp
  src/catch2/catch_matchers_templates.hpp
  tests/SelfTest/Baselines/automake.sw.approved.txt
  tests/SelfTest/Baselines/compact.sw.approved.txt
  tests/SelfTest/Baselines/console.std.approved.txt
  tests/SelfTest/Baselines/console.sw.approved.txt
  tests/SelfTest/Baselines/junit.sw.approved.txt
  tests/SelfTest/Baselines/sonarqube.sw.approved.txt
  tests/SelfTest/Baselines/tap.sw.approved.txt
  tests/SelfTest/Baselines/teamcity.sw.approved.txt
  tests/SelfTest/Baselines/xml.sw.approved.txt
  tests/SelfTest/UsageTests/Matchers.tests.cpp
Labels: Feature
