Repository catchorg/Catch2, pull requests merged in 2020-10, with the labels that each got.

#2039 Add WORKING_DIRECTORY to CatchAddTests.cmake commands
  contrib/CatchAddTests.cmake
Labels: Contrib

#2044 fix warning in extras/CatchAddTests.cmake
  extras/CatchAddTests.cmake
Labels: Contrib

#2045 Add AppMesh to Open Source projects using Catch
  docs/opensource-users.md
Labels: Documentation

#2072 Bump OpenCppCoverage to 0.9.9.0
  appveyor.yml
  tools/misc/installOpenCppCoverage.ps1
Labels: Development
