Repository catchorg/Catch2, pull requests merged in 2020-04, with the labels that each got.

#1907 Remove usage of __builtin_constant_p under IBM XL
  include/internal/catch_compiler_capabilities.h
Labels: 3rd party bug, BugFix

#1911 Use macro to determine whether std::uncaught_exceptions is available
  include/internal/catch_compiler_capabilities.h
Labels: Tweak

#1909 support custom allocators in vector Matchers
  include/internal/catch_matchers_vector.h
  projects/SelfTest/Baselines/compact.sw.approved.txt
  projects/SelfTest/Baselines/console.std.approved.txt
  projects/SelfTest/Baselines/console.sw.approved.txt
  projects/SelfTest/Baselines/junit.sw.approved.txt
  projects/SelfTest/Baselines/xml.sw.approved.txt
  projects/SelfTest/UsageTests/Matchers.tests.cpp
Labels: Tweak

#1916 Fix build with CATCH_CONFIG_DISABLE_EXCEPTIONS enabled
  include/internal/catch_assertionhandler.cpp
  include/internal/catch_interfaces_exception.h
Labels: BugFix
