Repository catchorg/Catch2, pull requests merged in 2020-11, with the labels that each got.

#2085 [DOCS] update from Hudson to Jenkins
  docs/command-line.md
Labels: Documentation

#2078 Silence -Wuseless-cast warning with GCC10
  src/catch2/internal/catch_test_macro_impl.hpp
Labels: Warnings issue

#2099 Adds license check in CI
  .github/workflows/validate-header-guards.yml
  tools/scripts/checkLicense.py
Labels: Development

#2070 Tests sorted according to random index instead of random hash
  include/internal/catch_test_case_registry_impl.cpp
Labels: Tweak request

#2112 Update cmake-integration.md
  docs/cmake-integration.md
Labels: Documentation
