Repository catchorg/Catch2, pull requests merged in 2020-03, with the labels that each got.

#1884 Fix: typo; remove trailing ",": Update tutorial.md
  docs/tutorial.md
Labels: Documentation

#1886 Fixed typo in "benchmark name" column width calculation.
  include/reporters/catch_reporter_console.cpp
  projects/ExtraTests/CMakeLists.txt
Labels: BugFix

#1891 Replace Deprecated C-Headers with the C++ ones
  include/internal/catch_debugger.cpp
Labels: Tweak

#1897 Updating documentation of open-source projects using Catch2
  docs/opensource-users.md
Labels: Documentation
