Repository catchorg/Catch2, pull requests merged in 2021-04, with the labels that each got.

#2206 Fix typos in the code base
  docs/contributing.md
  docs/matchers.md
  docs/release-notes.md
  examples/302-Gen-Table.cpp
  extras/ParseAndAddCatchTests.cmake
  src/catch2/internal/catch_enum_values_registry.cpp
Labels: Documentation

#2213 Fixed [dis]engage_platform declarations mismatch
  include/internal/catch_fatal_condition.cpp
Labels: BugFix

#2215 fixed inconsistent semicolon expansion in catch_discover_tests (Bug #2214)
  extras/CatchAddTests.cmake
Labels: Contrib

#2216 fixed inconsistent semicolon expansion in catch_discover_tests (Bug #2214)
  contrib/CatchAddTests.cmake
Labels: Contrib

#2205 Prepare to prevent Catch2 v3's tests from being run, and CTest targets from being added, if Catch2 is configured as a sub-project.
  CMakeLists.txt
Labels: Building and Packaging
