Repository catchorg/Catch2, pull requests merged in 2022-06, with the labels that each got.

#2446 Doc: correct the address of the link to the command-line doc in tutorial.md
  docs/tutorial.md
Labels: Documentation

#2436 Update documentation - add pkg-config examples.
  docs/migrate-v2-to-v3.md
  examples/010-TestCase.cpp
  examples/020-TestCase-1.cpp
  examples/030-Asn-Require-Check.cpp
  examples/100-Fix-Section.cpp
  examples/110-Fix-ClassFixture.cpp
  examples/120-Bdd-ScenarioGivenWhenThen.cpp
  examples/210-Evt-EventListeners.cpp
Labels: Documentation

#2450 Fix implicit long to double conversion
  src/catch2/benchmark/detail/catch_stats.hpp
Labels: Warnings issue

#2460 Fix package recipe for CMake Integration
  conanfile.py
Labels: Building and Packaging

#2459 Change Bazel XML support to depend upon BAZEL_TEST
  docs/configuration.md
  docs/deprecations.md
  src/catch2/catch_config.cpp
  tests/ExtraTests/CMakeLists.txt
Labels: Tweak

#2465 Update commercial-users.md
  docs/commercial-users.md
Labels: Documentation
