Repository catchorg/Catch2, pull requests merged in 2022-10, with the labels that each got.

#2530 Add support for building with Meson
  .github/workflows/linux-meson-builds.yml
  .gitignore
  meson.build
  src/catch2/meson.build
  tests/meson.build
  tools/scripts/releaseCommon.py
Labels: Building and Packaging

#2516 add versioning to shared libs
  src/CMakeLists.txt
Labels: Building and Packaging

#2546 Mute the sign conversion warning with explicit cast
  src/catch2/catch_tostring.hpp
Labels: Warnings issue

#2549 Link to SECTIONS doc at top of test fixtures page.
  docs/test-fixtures.md
Labels: Documentation

#2553 CatchMiscFunctions.cmake: Use PRIVATE for target_compile_options
  CMake/CatchMiscFunctions.cmake
Labels: Building and Packaging

#2550 Allow ANSI colour to be compiled on Windows
  include/internal/catch_console_colour.cpp
Labels: Tweak

#2554 Use console reporter's totals summary for compact reporter
  src/catch2/reporters/catch_reporter_compact.cpp
  src/catch2/reporters/catch_reporter_console.cpp
  src/catch2/reporters/catch_reporter_console.hpp
  src/catch2/reporters/catch_reporter_helpers.cpp
  src/catch2/reporters/catch_reporter_helpers.hpp
  tests/CMakeLists.txt
  tests/ExtraTests/CMakeLists.txt
  tests/SelfTest/Baselines/compact.sw.approved.txt
  tests/SelfTest/Baselines/compact.sw.multi.approved.txt
  tests/TestScripts/testConfigureDefaultReporter.py
Labels: Tweak

#2559 Update comparing-floating-point-numbers.md
  docs/comparing-floating-point-numbers.md
Labels: Documentation
