Repository catchorg/Catch2, pull requests merged in 2022-03, with the labels that each got.

#2390 Add eventpp and accessorpp to Catch2 users
  docs/opensource-users.md
Labels: Documentation

#2387 Fix broken Bazel build
  BUILD.bazel
  WORKSPACE
Labels: Building and Packaging

#2393 Fix filename as tag bug
  include/internal/catch_session.cpp
Labels: BugFix

#2394 Added TestCaseInfoHasher and tests.
  src/CMakeLists.txt
  src/catch2/catch_all.hpp
  src/catch2/internal/catch_test_case_info_hasher.cpp
  src/catch2/internal/catch_test_case_info_hasher.hpp
  src/catch2/internal/catch_test_case_registry_impl.cpp
  tests/CMakeLists.txt
  tests/SelfTest/Baselines/automake.sw.approved.txt
  tests/SelfTest/Baselines/automake.sw.multi.approved.txt
  tests/SelfTest/Baselines/compact.sw.approved.txt
  tests/SelfTest/Baselines/compact.sw.multi.approved.txt
  tests/SelfTest/Baselines/console.std.approved.txt
  tests/SelfTest/Baselines/console.sw.approved.txt
  tests/SelfTest/Baselines/console.sw.multi.approved.txt
  tests/SelfTest/Baselines/junit.sw.approved.txt
  tests/SelfTest/Baselines/junit.sw.multi.approved.txt
  tests/SelfTest/Baselines/sonarqube.sw.approved.txt
  tests/SelfTest/Baselines/sonarqube.sw.multi.approved.txt
  tests/SelfTest/Baselines/tap.sw.approved.txt
  tests/SelfTest/Baselines/tap.sw.multi.approved.txt
  tests/SelfTest/Baselines/teamcity.sw.approved.txt
  tests/SelfTest/Baselines/teamcity.sw.multi.approved.txt
  tests/SelfTest/Baselines/xml.sw.approved.txt
  tests/SelfTest/Baselines/xml.sw.multi.approved.txt
  tests/SelfTest/IntrospectiveTests/TestCaseInfoHasher.tests.cpp
Labels: BugFix
