Repository catchorg/Catch2, pull requests merged in 2023-12, with the labels that each got.

#2772 Fix compilation on Xbox platforms
  src/catch2/internal/catch_compiler_capabilities.hpp
Labels: Tweak

#2774 [DOC] Replaced broken link (fixes #2770)
  docs/ci-and-misc.md
Labels: Documentation

#2778 Fix typo in tostring.md
  docs/tostring.md
Labels: Documentation

#2769 Fix minor typos in overviews
  docs/cmake-integration.md
  docs/matchers.md
  docs/release-notes.md
  docs/skipping-passing-failing.md
  docs/test-cases-and-sections.md
  docs/tostring.md
  docs/why-catch.md
Labels: Documentation

#2781 Support MODULE.bazel
  MODULE.bazel
Labels: Building and Packaging

#2785 Make compiler flags for reproducible builds optional
  CMakeLists.txt
  src/CMakeLists.txt
Labels: Building and Packaging

#2784 Handle linking to liblog when [cross] building for Android using meson.
  src/catch2/meson.build
Labels: Building and Packaging

#2783 Improve Bazel support
  .bazelrc
  MODULE.bazel
  WORKSPACE.bazel
Labels: Building and Packaging
