Repository catchorg/Catch2, pull requests merged in 2023-03, with the labels that each got.

#2649 Bazel support: Update skylib version
  WORKSPACE.bazel
Labels: Building and Packaging

#2658 Add more open source libraries using Catch
  docs/opensource-users.md
Labels: Documentation

#2657 Fixed extras installation and shard impl script detection
  CMakeLists.txt
  extras/CatchShardTests.cmake
Labels: Tweak, Extras
