Repository catchorg/Catch2, pull requests merged in 2023-01, with the labels that each got.

#2612 Update command-line.md
  docs/command-line.md
Labels: Documentation

#2611 Fix build with GCC 13 (add missing <cstdint> include)
  src/catch2/catch_test_case_info.hpp
  src/catch2/internal/catch_string_manip.hpp
  src/catch2/internal/catch_xmlwriter.cpp
Labels: BugFix

#2360 Add new SKIP macro for skipping tests at runtime
  docs/Readme.md
  docs/command-line.md
  docs/deprecations.md
  docs/skipping.md
  src/catch2/catch_session.cpp
  src/catch2/catch_test_macros.hpp
  src/catch2/catch_totals.cpp
  src/catch2/catch_totals.hpp
  src/catch2/interfaces/catch_interfaces_reporter.hpp
  src/catch2/internal/catch_assertion_handler.cpp
  src/catch2/internal/catch_assertion_handler.hpp
  src/catch2/internal/catch_console_colour.hpp
  src/catch2/internal/catch_exception_translator_registry.cpp
  src/catch2/internal/catch_result_type.hpp
  src/catch2/internal/catch_run_context.cpp
  src/catch2/internal/catch_test_failure_exception.hpp
  src/catch2/reporters/catch_reporter_automake.cpp
  src/catch2/reporters/catch_reporter_compact.cpp
  src/catch2/reporters/catch_reporter_console.cpp
  src/catch2/reporters/catch_reporter_helpers.cpp
  src/catch2/reporters/catch_reporter_junit.cpp
  src/catch2/reporters/catch_reporter_sonarqube.cpp
  src/catch2/reporters/catch_reporter_tap.cpp
  src/catch2/reporters/catch_reporter_teamcity.cpp
  src/catch2/reporters/catch_reporter_xml.cpp
  tests/CMakeLists.txt
  tests/ExtraTests/CMakeLists.txt
  tests/ExtraTests/X93-AllSkipped.cpp
  tests/SelfTest/Baselines/automake.sw.approved.txt
  tests/SelfTest/Baselines/automake.sw.multi.approved.txt
  tests/SelfTest/Baselines/compact.sw.approved.txt
  tests/SelfTest/Baselines/compact.sw.multi.approved.txt
  tests/SelfTest/Baselines/console.std.approved.txt
  tests/SelfTest/Baselines/console.sw.approved.txt
  tests/SelfTest/Baselines/console.sw.multi.approved.txt
  tests/SelfTest/Baselines/default.sw.multi.approved.txt
  tests/SelfTest/Baselines/junit.sw.approved.txt
  tests/SelfTest/Baselines/junit.sw.multi.approved.txt
  tests/SelfTest/Baselines/sonarqube.sw.approved.txt
  tests/SelfTest/Baselines/sonarqube.sw.multi.approved.txt
  tests/SelfTest/Baselines/tap.sw.approved.txt
  tests/SelfTest/Baselines/tap.sw.multi.approved.txt
  tests/SelfTest/Baselines/teamcity.sw.approved.txt
  tests/SelfTest/Baselines/teamcity.sw.multi.approved.txt
  tests/SelfTest/Baselines/xml.sw.approved.txt
  tests/SelfTest/Baselines/xml.sw.multi.approved.txt
  tests/SelfTest/UsageTests/Skip.tests.cpp
Labels: Feature

#2622 Document template macros are in spearate header
  docs/test-cases-and-sections.md
Labels: Documentation
