Repository catchorg/Catch2, pull requests merged in 2023-09, with the labels that each got.

#2742 Update meson.build to fix #2722
  src/catch2/meson.build
Labels: Building and Packaging

#2747 correct argument references in CatchAddTests.cmake
  extras/CatchAddTests.cmake
Labels: Extras

#2732 fix some bugprone-macro-parentheses warnings
  src/catch2/internal/catch_test_macro_impl.hpp
  src/catch2/internal/catch_test_registry.hpp
Labels: Warnings issue

#2739 Catch.cmake: Support CMake multi-config with PRE_TEST discovery mode
  extras/Catch.cmake
Labels: Extras

#2750 why-catch.md: Add JetBrains survey link
  docs/why-catch.md
Labels: Documentation
