Repository catchorg/Catch2, pull requests merged in 2024-03, with the labels that each got.

#2841 Stop repeating conditional in endif()
  CMakeLists.txt
  extras/ParseAndAddCatchTests.cmake
  tests/CMakeLists.txt
  tests/ExtraTests/CMakeLists.txt
Labels: Building and Packaging

#2838 Ignore C++98 related compiler warnings
  tests/SelfTest/TestRegistrations.cpp
  tests/SelfTest/UsageTests/Misc.tests.cpp
Labels: Warnings issue

#2839 Add workaround for unguarded use of __has_extension
  src/catch2/internal/catch_platform.hpp
Labels: 3rd party bug

#2840 Add workaround for unguarded use of __has_extension (for v2.x)
  include/internal/catch_platform.h
Labels: 3rd party bug

#2831 Improve Conan recipe support
  .conan/test_package/CMakeLists.txt
  .conan/test_package/conanfile.py
  .github/workflows/package-manager-builds.yaml
  conanfile.py
Labels: Building and Packaging

#2850 Mention SUCCEED along with FAIL in logging.md
  docs/logging.md
Labels: Documentation
