Repository catchorg/Catch2, pull requests merged in 2024-02, with the labels that each got.

#2812 Add Bazel instructions to integration docs
  docs/cmake-integration.md
Labels: Documentation

#2807 Clarify unit of test duration in docs
  docs/command-line.md
Labels: Documentation

#2804 Fix number of current reporter
  docs/reporters.md
Labels: Documentation

#2805 Conan v2
  .conan/test_package/CMakeLists.txt
  .conan/test_package/conanfile.py
  .github/workflows/package-manager-builds.yaml
  .gitignore
  conanfile.py
Labels: Building and Packaging

#2793 Improve tutorial.md with link to two-file setup instructions.
  docs/tutorial.md
Labels: Documentation

#2815 Set target_link_libraries visibility to PRIVATE for linking android log
  src/CMakeLists.txt
Labels: Building and Packaging

#2821 fix double promotion in catch_approx.cpp
  src/catch2/catch_approx.cpp
Labels: Warnings issue

#2823 avoid useless case (FDuration pointer deref to FDuration=
  src/catch2/benchmark/detail/catch_analyse.cpp
Labels: Warnings issue
