Repository catchorg/Catch2, pull requests merged in 2024-08, with the labels that each got.

#2885 TEST_CASE_FIXTURE: A new fixture macro for allowing persistent fixtures throughout a TEST_CASE
  docs/cmake-integration.md
  docs/list-of-examples.md
  docs/other-macros.md
  docs/test-fixtures.md
  examples/111-Fix-PersistentFixture.cpp
  examples/CMakeLists.txt
  src/catch2/catch_test_case_info.hpp
  src/catch2/catch_test_macros.hpp
  src/catch2/interfaces/catch_interfaces_test_invoker.hpp
  src/catch2/internal/catch_run_context.cpp
  src/catch2/internal/catch_test_registry.cpp
  src/catch2/internal/catch_test_registry.hpp
  tests/ExtraTests/X02-DisabledMacros.cpp
  tests/SelfTest/Baselines/automake.sw.approved.txt
  tests/SelfTest/Baselines/automake.sw.multi.approved.txt
  tests/SelfTest/Baselines/compact.sw.approved.txt
  tests/SelfTest/Baselines/compact.sw.multi.approved.txt
  tests/SelfTest/Baselines/console.std.approved.txt
  tests/SelfTest/Baselines/console.sw.approved.txt
  tests/SelfTest/Baselines/console.sw.multi.approved.txt
  tests/SelfTest/Baselines/junit.sw.approved.txt
  tests/SelfTest/Baselines/junit.sw.multi.approved.txt
  tests/SelfTest/Baselines/sonarqube.sw.approved.txt
  tests/SelfTest/Baselines/sonarqube.sw.multi.approved.txt
  tests/SelfTest/Baselines/tap.sw.approved.txt
  tests/SelfTest/Baselines/tap.sw.multi.approved.txt
  tests/SelfTest/Baselines/teamcity.sw.approved.txt
  tests/SelfTest/Baselines/teamcity.sw.multi.approved.txt
  tests/SelfTest/Baselines/xml.sw.approved.txt
  tests/SelfTest/Baselines/xml.sw.multi.approved.txt
  tests/SelfTest/UsageTests/Class.tests.cpp
Labels: Feature

#2898 Fix typo in test-cases-and-sections.md
  docs/test-cases-and-sections.md
Labels: Documentation

#2867 Move header from internal
  src/CMakeLists.txt
  src/catch2/catch_all.hpp
  src/catch2/catch_case_sensitive.hpp
  src/catch2/internal/catch_wildcard_pattern.hpp
  src/catch2/matchers/catch_matchers_string.hpp
  src/catch2/meson.build
Labels: Tweak

#2878 Respect path order of DL_PATHS in catch_discover_tests
  extras/CatchAddTests.cmake
Labels: Extras
