Repository catchorg/Catch2, pull requests merged in 2024-09, with the labels that each got.

#2904 Suppress GCC useless-cast warning from CHECK_THROWS_MATCHES
  src/catch2/matchers/internal/catch_matchers_impl.hpp
Labels: Warnings issue

#2906 Simplify instructions by not changing directories for the ctest command
  docs/contributing.md
  tools/scripts/buildAndTest.cmd
  tools/scripts/buildAndTest.sh
Labels: Documentation

#2905 Fix bug in TokenStream parser
  src/catch2/internal/catch_clara.cpp
  tests/SelfTest/Baselines/automake.sw.approved.txt
  tests/SelfTest/Baselines/automake.sw.multi.approved.txt
  tests/SelfTest/Baselines/compact.sw.approved.txt
  tests/SelfTest/Baselines/compact.sw.multi.approved.txt
  tests/SelfTest/Baselines/console.std.approved.txt
  tests/SelfTest/Baselines/console.sw.approved.txt
  tests/SelfTest/Baselines/console.sw.multi.approved.txt
  tests/SelfTest/Baselines/junit.sw.approved.txt
  tests/SelfTest/Baselines/junit.sw.multi.approved.txt
  tests/SelfTest/Baselines/sonarqube.sw.approved.txt
  tests/SelfTest/Baselines/sonarqube.sw.multi.approved.txt
  tests/SelfTest/Baselines/tap.sw.approved.txt
  tests/SelfTest/Baselines/tap.sw.multi.approved.txt
  tests/SelfTest/Baselines/teamcity.sw.approved.txt
  tests/SelfTest/Baselines/teamcity.sw.multi.approved.txt
  tests/SelfTest/Baselines/xml.sw.approved.txt
  tests/SelfTest/Baselines/xml.sw.multi.approved.txt
  tests/SelfTest/IntrospectiveTests/Clara.tests.cpp
Labels: BugFix
